//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 11:20:46 AM ICT 
//


package org.opencps.dossiermgt.lgsp.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocPapers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocPapers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaperName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PaperType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocPapers", propOrder = {
    "paperName",
    "amount",
    "paperType"
})
public class DocPapers {

    @XmlElement(name = "PaperName", required = true)
    protected String paperName;
    @XmlElement(name = "Amount")
    protected int amount;
    @XmlElement(name = "PaperType")
    protected int paperType;

    /**
     * Gets the value of the paperName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * Sets the value of the paperName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperName(String value) {
        this.paperName = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public int getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(int value) {
        this.amount = value;
    }

    /**
     * Gets the value of the paperType property.
     * 
     */
    public int getPaperType() {
        return paperType;
    }

    /**
     * Sets the value of the paperType property.
     * 
     */
    public void setPaperType(int value) {
        this.paperType = value;
    }

}
