//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.21 at 11:18:05 AM ICT 
//


package org.opencps.api.registrationtemplate.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="formScript" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "formScript"
})
@XmlRootElement(name = "RegistrationTemplateFormScriptInputUpdateModel")
public class RegistrationTemplateFormScriptInputUpdateModel {

    protected String formScript;

    /**
     * Gets the value of the formScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormScript() {
        return formScript;
    }

    /**
     * Sets the value of the formScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormScript(String value) {
        this.formScript = value;
    }

}
