package backend.api.rest.application.utils;

import com.liferay.portal.kernel.search.Field;

public class ConstantTerm {
	public static final String STATISTIC_JSON = "org.opencps.v21.statisticjson";
	public static final String HTTP_REQUEST = "HTTP.REQUEST";
	public static final String ES_API_URL = "org.opencps.v21.elasticsearch.api.url";
	public static final String MULTIPLE_ES_API_URL = "org.opencps.v21.multiple.elasticsearch.api.url";
	public static final String HTTP_HEADERS_ACCEPT = "Accept";
	public static final String HTTP_HEADERS_CONTENT_TYPE = "Content-Type";
	public static final String APPLICATION_JSON_CONTENT_TYPE = "org.opencps.v21.contenttype.application.json";
	public static final String MODIFIED_DATE_SORTABLE = Field.MODIFIED_DATE + "_sortable";
	
	public static final String JSON_TOTAL = "total";
	public static final String JSON_DATA = "data";
	public static final String JSON_STEP_CODE = "stepCode";
	public static final String JSON_STEP_NAME = "stepName";
	public static final String JSON_DOSSIER_STATUS = "dossierStatus";
	public static final String JSON_DOSSIER_SUB_STATUS = "dossierSubStatus";
	public static final String JSON_TOTAL_COUNT = "totalCount";
	public static final String JSON_DENIED_COUNT = "deniedCount";
	public static final String JSON_CANCELLED_COUNT = "cancelledCount";
	public static final String JSON_PROCESS_COUNT = "processCount";
	public static final String JSON_REMAINING_COUNT = "remainingCount";
	public static final String JSON_RECEIVED_COUNT = "receivedCount";
	public static final String JSON_ONEGATE_COUNT = "onegateCount";
	public static final String JSON_ONLINE_COUNT = "onlineCount";
	public static final String JSON_RELEASE_COUNT = "releaseCount";
	public static final String JSON_BETIMES_COUNT = "betimesCount";
	public static final String JSON_ONTIME_COUNT = "ontimeCount";
	public static final String JSON_OVERTIME_COUNT = "overtimeCount";
	public static final String JSON_OVERTIME_INSIDE = "overtimeInside";
	public static final String JSON_OVERTIME_OUTSIDE = "overtimeOutside";
	public static final String JSON_DONE_COUNT = "doneCount";
	public static final String JSON_RELEASING_COUNT = "releasingCount";
	public static final String JSON_UNRESOLVED_COUNT = "unresolvedCount";
	public static final String JSON_PROCESSING_COUNT = "processingCount";
	public static final String JSON_UNDUE_COUNT = "undueCount";
	public static final String JSON_OVERDUE_COUNT = "overdueCount";
	public static final String JSON_OUTSIDE_COUNT = "outsideCount";
	public static final String JSON_WAITING_COUNT = "waitingCount";
	public static final String JSON_ONTIME_PERCENTAGE = "ontimePercentage";
	public static final String JSON_REPORT_TYPE = "reportType";
	public static final String JSON_FORM_REPORT = "formReport";
	public static final String JSON_FORM_DATA = "formData";
	public static final String JSON_YEAR = "year";
	public static final String JSON_MONTH = "month";
	public static final String JSON_GOV_AGENCY_NAME = "govAgencyName";
	public static final String JSON_FROMDATE = "fromDate";
	public static final String JSON_TODATE = "toDate";
	public static final String JSON_FROMSTATISTICDATE = "fromStatisticDate";
	public static final String JSON_TOSTATISTICDATE = "toStatisticDate";
	public static final String JSON_ACTION_USER = "actionUser";
	public static final String JSON_DOMAIN_NAME = "domainName";
	public static final String JSON_SERVICES = "services";
	public static final String JSON_SERVICE_CODE = "serviceCode";
	public static final String JSON_SERVICE_NAME = "serviceName";
	public static final String JSON_DOSSIERS = "dossiers";
	public static final String JSON_FLAG_AGENCY = "flagAgency";
	public static final String JSON_NODATA = "nodata";
	public static final String JSON_TOTAL_3 = "total_3";
	public static final String JSON_TOTAL_4 = "total_4";
	public static final String JSON_TOTAL_5 = "total_5";
	public static final String JSON_TOTAL_6 = "total_6";
	public static final String JSON_TOTAL_7 = "total_7";
	public static final String JSON_TOTAL_8 = "total_8";
	public static final String JSON_TOTAL_9 = "total_9";
	public static final String JSON_TOTAL_10 = "total_10";
	public static final String JSON_TOTAL_11 = "total_11";
	public static final String JSON_TOTAL_12 = "total_12";
	public static final String JSON_TOTAL_13 = "total_13";
	public static final String JSON_TOTAL_14 = "total_14";
	public static final String JSON_TOTAL_15 = "total_15";
	public static final String JSON_TOTAL_16 = "total_16";
	public static final String JSON_TOTAL_17 = "total_17";
	public static final String JSON_TOTAL_18 = "total_18";
	public static final String JSON_TOTAL_19 = "total_19";
	public static final String JSON_TOTAL_20 = "total_20";
	public static final String JSON_TOTAL_21 = "total_21";
	public static final String JSON_TOTAL_22 = "total_22";
	public static final String JSON_TOTAL_23 = "total_23";
	public static final String JSON_TOTAL_24 = "total_24";
	public static final String JSON_TOTAL_25 = "total_25";
	
	public static final String UTF_8 = "UTF-8";
	public static final String APPLICATION_EXCEL_CONTENT_TYPE = "org.opencps.v21.contenttype.application.excel";
	public static final String APPLICATION_WORD_CONTENT_TYPE = "org.opencps.v21.contenttype.application.word";
	public static final String APPLICATION_PDF_CONTENT_TYPE = "org.opencps.v21.contenttype.application.pdf";
	public static final String JASPER_ENGINE_PREVIEW_DESTINATION = "jasper/engine/preview/destination";
	public static final String TEST_JSON = "test.json";
	public static final String PDF_TYPE = "pdf";

	public static final String EXTENSION_DOC = "org.opencps.v21.extension.doc";
	public static final String EXTENSION_XLS = "org.opencps.v21.extension.xls";
	public static final String EXTENSION_PDF = "org.opencps.v21.extension.pdf";	
	
	public static final String REPORT_01 = "REPORT_01";
	public static final String REPORT_02 = "REPORT_02";
	public static final String REPORT_03 = "REPORT_03";
	public static final String REPORT_04 = "REPORT_04";
	public static final String REPORT_05 = "REPORT_05";
	public static final String REPORT_06 = "REPORT_06";
	public static final String REPORT_07 = "REPORT_07";
	public static final String REPORT_08 = "REPORT_08";
	public static final String REPORT_09 = "REPORT_09";
	public static final String REPORT_10 = "REPORT_10";	
}
