//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2017.10.23 at 09:44:18 AM ICT 
//


package org.opencps.dossiermgt.input.model;

public class DossierMultipleInputModel {
	protected String serviceCode;
	protected String govAgencyCode;
	protected String dossierTemplateNo;
	protected Integer originality;
	private String dossiers;
	private String dossierMarkArr;
	private String dossierFileArr;
	private String payment;

	public String getServiceCode() {
		return serviceCode;
	}
	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}
	public String getGovAgencyCode() {
		return govAgencyCode;
	}
	public void setGovAgencyCode(String govAgencyCode) {
		this.govAgencyCode = govAgencyCode;
	}
	public String getDossierTemplateNo() {
		return dossierTemplateNo;
	}
	public void setDossierTemplateNo(String dossierTemplateNo) {
		this.dossierTemplateNo = dossierTemplateNo;
	}
	public Integer getOriginality() {
		return originality;
	}
	public void setOriginality(Integer originality) {
		this.originality = originality;
	}
	public String getDossiers() {
		return dossiers;
	}
	public void setDossiers(String dossiers) {
		this.dossiers = dossiers;
	}
	public String getDossierMarkArr() {
		return dossierMarkArr;
	}
	public void setDossierMarkArr(String dossierMarkArr) {
		this.dossierMarkArr = dossierMarkArr;
	}
	public String getDossierFileArr() {
		return dossierFileArr;
	}
	public void setDossierFileArr(String dossierFileArr) {
		this.dossierFileArr = dossierFileArr;
	}
	public String getPayment() {
		return payment;
	}
	public void setPayment(String payment) {
		this.payment = payment;
	}

}
