create table opencps_person_statistic (
	uuid_ VARCHAR(75) null,
	personStatisticId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName VARCHAR(255) null,
	createDate DATE null,
	modifiedDate DATE null,
	month INTEGER,
	year INTEGER,
	govAgencyCode VARCHAR(255) null,
	govAgencyName TEXT null,
	employeeId LONG,
	votingCode VARCHAR(75) null,
	votingSubject TEXT null,
	totalVoted INTEGER,
	veryGoodCount INTEGER,
	goodCount INTEGER,
	badCount INTEGER,
	percentVeryGood INTEGER,
	percentGood INTEGER,
	percentBad INTEGER,
	totalCount INTEGER
);

create table opencps_statistic (
	uuid_ VARCHAR(75) null,
	dossierStatisticId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName VARCHAR(255) null,
	createDate DATE null,
	modifiedDate DATE null,
	month INTEGER,
	year INTEGER,
	totalCount INTEGER,
	deniedCount INTEGER,
	cancelledCount INTEGER,
	processCount INTEGER,
	remainingCount INTEGER,
	receivedCount INTEGER,
	onlineCount INTEGER,
	onegateCount INTEGER,
	releaseCount INTEGER,
	betimesCount INTEGER,
	ontimeCount INTEGER,
	overtimeCount INTEGER,
	doneCount INTEGER,
	releasingCount INTEGER,
	unresolvedCount INTEGER,
	processingCount INTEGER,
	undueCount INTEGER,
	overdueCount INTEGER,
	pausingCount INTEGER,
	ontimePercentage INTEGER,
	govAgencyCode VARCHAR(255) null,
	groupAgencyCode TEXT null,
	govAgencyName TEXT null,
	domainCode VARCHAR(255) null,
	domainName TEXT null,
	reporting INTEGER,
	overtimeInside INTEGER,
	overtimeOutside INTEGER,
	interoperatingCount INTEGER,
	waitingCount INTEGER,
	outsideCount INTEGER,
	insideCount INTEGER,
	system VARCHAR(75) null,
	viaPostalCount INTEGER,
	notViaPostalCount INTEGER,
	saturdayCount INTEGER,
	dossierOnline3Count INTEGER,
	dossierOnline4Count INTEGER,
	receiveDossierSatCount INTEGER,
	releaseDossierSatCount INTEGER,
	fromViaPostalCount INTEGER,
	processingInAPeriodCount INTEGER,
	releaseInAPeriodCount INTEGER
);

create table opencps_statistic_manual (
	uuid_ VARCHAR(75) null,
	dossierStatisticId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName VARCHAR(255) null,
	createDate DATE null,
	modifiedDate DATE null,
	month INTEGER,
	year INTEGER,
	totalCount INTEGER,
	deniedCount INTEGER,
	cancelledCount INTEGER,
	processCount INTEGER,
	remainingCount INTEGER,
	receivedCount INTEGER,
	onlineCount INTEGER,
	onegateCount INTEGER,
	releaseCount INTEGER,
	betimesCount INTEGER,
	ontimeCount INTEGER,
	overtimeCount INTEGER,
	doneCount INTEGER,
	releasingCount INTEGER,
	unresolvedCount INTEGER,
	processingCount INTEGER,
	undueCount INTEGER,
	overdueCount INTEGER,
	pausingCount INTEGER,
	ontimePercentage INTEGER,
	govAgencyCode VARCHAR(255) null,
	groupAgencyCode TEXT null,
	govAgencyName TEXT null,
	domainCode VARCHAR(255) null,
	domainName TEXT null,
	reporting BOOLEAN,
	overtimeInside INTEGER,
	overtimeOutside INTEGER,
	interoperatingCount INTEGER,
	waitingCount INTEGER,
	outsideCount INTEGER,
	insideCount INTEGER,
	system VARCHAR(75) null,
	viaPostalCount INTEGER,
	notViaPostalCount INTEGER,
	saturdayCount INTEGER,
	dossierOnline3Count INTEGER,
	dossierOnline4Count INTEGER,
	receiveDossierSatCount INTEGER,
	releaseDossierSatCount INTEGER,
	fromViaPostalCount INTEGER
);

create table opencps_statistic_mgt (
	uuid_ VARCHAR(75) null,
	dossierStatisticMgtId LONG not null primary key,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	month INTEGER,
	year INTEGER,
	totalCount INTEGER,
	processCount INTEGER,
	remainingCount INTEGER,
	receivedCount INTEGER,
	onlineCount INTEGER,
	onegateCount INTEGER,
	releaseCount INTEGER,
	betimesCount INTEGER,
	ontimeCount INTEGER,
	overtimeCount INTEGER,
	doneCount INTEGER,
	releasingCount INTEGER,
	processingCount INTEGER,
	undueCount INTEGER,
	overdueCount INTEGER,
	ontimePercentage INTEGER,
	waitingCount INTEGER,
	govAgencyCode VARCHAR(75) null,
	govAgencyName VARCHAR(75) null,
	domainCode VARCHAR(75) null,
	domainName VARCHAR(75) null,
	serviceCode VARCHAR(75) null,
	serviceName VARCHAR(75) null,
	groupBy INTEGER
);

create table opencps_voting_statistic (
	uuid_ VARCHAR(75) null,
	votingStatisticId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName VARCHAR(255) null,
	createDate DATE null,
	modifiedDate DATE null,
	month INTEGER,
	year INTEGER,
	govAgencyCode VARCHAR(255) null,
	govAgencyName TEXT null,
	domainCode VARCHAR(255) null,
	domainName TEXT null,
	votingCode VARCHAR(255) null,
	votingSubject TEXT null,
	totalVoted INTEGER,
	veryGoodCount INTEGER,
	goodCount INTEGER,
	badCount INTEGER,
	percentVeryGood INTEGER,
	percentGood INTEGER,
	percentBad INTEGER,
	totalCount INTEGER
);