package org.opencps.dossiermgt.constants;

public class DossierTerm {
	public static final String DOSSIER_ID = "dossierId";
	public static final String GROUP_ID = "groupId";
	public static final String USER_ID = "userId";
	public static final String CREATE_DATE = "createDate";
	public static final String MODIFIED_DATE = "modifiedDate";
	public static final String REFERENCE_UID = "referenceUid";
	public static final String COUNTER = "counter";
	public static final String SERVICE_CODE = "serviceCode";
	public static final String SERVICE_NAME = "serviceName";
	public static final String GOV_AGENCY_CODE = "govAgencyCode";
	public static final String GOV_AGENCY_NAME = "govAgencyName";
	public static final String APPLICANT_NAME = "applicantName";
	public static final String APPLICANT_ID_TYPE = "applicantIdType";
	public static final String APPLICANT_ID_NO = "applicantIdNo";
	public static final String APPLICANT_ID_DATE = "applicantIdDate";
	public static final String ADDRESS = "address";
	public static final String CITY_CODE = "cityCode";
	public static final String CITY_NAME = "cityName";
	public static final String DISTRICT_CODE = "districtCode";
	public static final String DISTRICT_NAME = "districtName";
	public static final String WARD_CODE = "wardCode";
	public static final String WARD_NAME = "wardName";
	public static final String CONTACT_NAME = "contactName";
	public static final String CONTACT_TEL_NO = "contactTelNo";
	public static final String CONTACT_EMAIL = "contactEmail";
	public static final String DOSSIER_TEMPLATE_NO = "dossierTemplateNo";
	public static final String DOSSIER_NOTE = "dossierNote";
	public static final String SUBMISSION_NOTE = "submissionNote";
	public static final String APPLICANT_NOTE = "applicantNote";
	public static final String BRIEF_NOTE = "briefNote";
	public static final String DOSSIER_NO = "dossierNo";
	public static final String SUBMITTING = "submitting";
	public static final String SUBMIT_DATE = "submitDate";
	public static final String RECEIVE_DATE = "receiveDate";
	public static final String PROCESS_DATE = "processDate";
	public static final String EXTEND_DATE = "extendDate";
	public static final String RECEIVE_DATE_SORTABLE = "receiveDate_sortable";
	public static final String RECEIVE_DATE_TIMESTAMP = "receiveDateTimestamp";
	public static final String DUE_DATE = "dueDate";
	public static final String DUE_DATE_TIMESTAMP = "dueDateTimestamp";
	public static final String RELEASE_DATE = "releaseDate";
	public static final String RELEASE_DATE_TIMESTAMP = "releaseDateTimestamp";
	public static final String FINISH_DATE = "finishDate";
	public static final String FINISH_DATE_TIMESTAMP = "finishDateTimestamp";
	public static final String CANCELLING_DATE = "cancellingDate";
	public static final String CANCELLING_DATE_TIMESTAMP = "cancellingDateTimestamp";
	public static final String CORRECTING_DATE = "correctingDate";
	public static final String CORRECTING_DATE_TIMESTAMP = "correctingDateTimestamp";
	public static final String DOSSIER_STATUS = "dossierStatus";
	public static final String DOSSIER_STATUS_TEXT = "dossierStatusText";
	public static final String DOSSIER_SUB_STATUS = "dossierSubStatus";
	public static final String DOSSIER_SUB_STATUS_TEXT = "dossierSubStatusText";
	public static final String FOLDER_ID = "folderId";
	public static final String DOSSIER_ACTION_ID = "dossierActionId";
	public static final String VIA_POSTAL = "viaPostal";
	public static final String POSTAL_ADDRESS = "postalAddress";
	public static final String POSTAL_CITY_CODE = "postalCityCode";
	public static final String POSTAL_CITY_NAME = "postalCityName";
	public static final String POSTAL_TEL_NO = "postalTelNo";
	public static final String PASSWORD = "password";
	public static final String NOTIFICATION = "notification";
	public static final String ONLINE = "online";
	public static final String SERVER_NO = "serverNo";
	public static final String YEAR_DOSSIER = "yearDossier";
	public static final String MONTH_DOSSIER = "monthDossier";
	public static final String LAST_ACTION_DATE = "lastActionDate";
	public static final String LAST_ACTION_CODE = "lastActionCode";
	public static final String LAST_ACTION_NAME = "lastActionName";
	public static final String LAST_ACTION_USER = "lastActionUser";
	public static final String LAST_ACTION_NOTE = "lastActionNote";
	public static final String STEP_CODE = "stepCode";
	public static final String STEP_NAME = "stepName";
	public static final String STEP_DUE_DATE = "stepDuedate";
	public static final String STEP_OVER_DUE = "stepOverdue";
	public static final String DOSSIER_OVER_DUE = "dossierOverdue";
	public static final String ACTION_USERIDS = "actionUserIds";
	
	public static final String STATUS = "status";
	public static final String SUBSTATUS = "subStatus";
	public static final String AGENCY = "agency";
	public static final String SERVICE = "service";
	public static final String TEMPLATE = "template";
	public static final String YEAR = "year";
	public static final String MONTH = "month";
	public static final String OWNER = "owner";
	public static final String FOLLOW = "follow";
	public static final String STEP = "step";
	public static final String TOP = "top";
	public static final String STATE = "state";
	public static final String TOTAL = "total";

	public static final String FROM_RECEIVEDATE = "fromReceiveDate";
	public static final String TO_RECEIVEDATE = "toReceiveDate";
	public static final String CERT_NO = "so_chung_chi";
	public static final String FROM_CERT_DATE = "tu_ngay_ky_cc";
	public static final String TO_CERT_DATE = "den_ngay_ky_cc";
	public static final String CERT_DATE = "ngay_ky_cc";
	public static final String DOSSIER_ID_CTN = "dossierIdCTN";
	public static final String FROM_SUBMIT_DATE = "fromSubmitDate";
	public static final String TO_SUBMIT_DATE = "toSubmitDate";
	
	public static final String DOSSIER_NO_SEARCH = "dossierNoSearch";
	public static final String CERT_NO_SEARCH = "certNoSearch";
	public static final String ACTION_MAPPING_USERID = "actionMappingUserId";
	public static final String ENDORSEMENT_DATE= "endorsementDate";
	public static final String ENDORSEMENT_DATE_TIMESTAMP = "endorsementDateTimestamp";
	public static final String DOSSIER_ACTION_ID_PENDING = "dossierActionIdPending";
	public static final String NOT_STATE = "notState";
	public static final String STATUS_REG = "statusReg";
	public static final String NOT_STATUS_REG = "notStatusReg";
	public static final String LOCK_STATE = "lockState";
	//LamTV: Add constants
	public static final String ORIGINALLITY = "originality";
	public static final String SECET_KEY = "secetKey";
	public static final String ASSIGNED = "assigned";
	
	public static final int ORIGINALITY_DVCTT = 1;
	public static final int ORIGINALITY_LIENTHONG = 2;
	public static final int ORIGINALITY_MOTCUA = 3;
		
	public static final String POSTAL_SERVICE_CODE = "postalServiceCode";
	public static final String POSTAL_DISTRICT_CODE = "postalDistrictCode";
	public static final String POSTAL_WARD_CODE = "postalWardCode";
	
	public static final String DOSSIER_STATUS_INTEROPERATING = "interoperating";
	public static final String DOSSIER_STATUS_NEW = "new";
	public static final String DOSSIER_STATUS_RECEIVING = "receiving";
	public static final String DOSSIER_STATUS_WAITING = "waiting";
	public static final String DOSSIER_STATUS_PROCESSING = "processing";
	public static final String DOSSIER_STATUS_PAUSING = "pausing";
	public static final String DOSSIER_STATUS_POSTING = "posting";
	public static final String DOSSIER_STATUS_CORRECTING = "correcting";
	public static final String DOSSIER_STATUS_CANCELLING = "cancelling";
	public static final String DOSSIER_STATUS_RELEASING = "releasing";
	public static final String DOSSIER_STATUS_DENIED = "denied";
	public static final String DOSSIER_STATUS_UNRESOLVED = "unresolved";
	public static final String DOSSIER_STATUS_CANCELLED = "cancelled";
	public static final String DOSSIER_STATUS_DONE = "done";
	//LamTV_Add
	public static final String DOSSIER_STATUS_STEP = "statusStep";
	public static final String DOSSIER_SUBSTATUS_STEP = "subStatusStep";
	public static final String USER_NOTE = "userNote";
	public static final String DURATION_COUNT = "durationCount";
	public static final String DURATION_UNIT = "durationUnit";
	public static final String SAMPLE_COUNT = "sampleCount";
	public static final String DELEGATE_ADDRESS = "delegateAddress";
	
	public static final String DOSSIER_MARKS = "dossierMarks";
	public static final String REGISTER_BOOK_CODE = "registerBookCode";
	public static final String SEQUENCE_ROLE = "sequenceRole";
	public static final String NEXT_SEQUENCE_ROLE = "nextSequenceRole";
	public static final String ACTION_USER = "actionUser";
	public static final String MAPPING_PERMISSION = "permission";
	public static final String MAPPING_DOSSIER = "dossiers";

	public static final String DOMAIN_CODE = "domainCode";
	public static final String DOMAIN_NAME = "domainName";
	public static final String ORIGIN_DOSSIER_ID = "originDossierId";

	public static final int GARBAGE_COLLECTOR_TIME = 30; //minutes
	
	public static final String PUBLISH_DOSSIER_DESTINATION = "publish/dossier/in/destination";
	public static final String YEAR_FINISH = "yearFinish";
	public static final String MONTH_FINISH = "monthFinish";
	public static final String STATISTIC = "statistic";
}
