//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.20 at 05:56:58 PM ICT 
//


package org.opencps.api.serviceinfo.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opencps.serviceinfo.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opencps.serviceinfo.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StatisticsLevelResultsModel }
     * 
     */
    public StatisticsLevelResultsModel createStatisticsLevelResultsModel() {
        return new StatisticsLevelResultsModel();
    }

    /**
     * Create an instance of {@link StatisticsLevel }
     * 
     */
    public StatisticsLevel createStatisticsLevel() {
        return new StatisticsLevel();
    }

    /**
     * Create an instance of {@link ServiceInfoResultsModel }
     * 
     */
    public ServiceInfoResultsModel createServiceInfoResultsModel() {
        return new ServiceInfoResultsModel();
    }

    /**
     * Create an instance of {@link ServiceInfoModel }
     * 
     */
    public ServiceInfoModel createServiceInfoModel() {
        return new ServiceInfoModel();
    }

    /**
     * Create an instance of {@link FileTemplateResultsModel }
     * 
     */
    public FileTemplateResultsModel createFileTemplateResultsModel() {
        return new FileTemplateResultsModel();
    }

    /**
     * Create an instance of {@link FileTemplates }
     * 
     */
    public FileTemplates createFileTemplates() {
        return new FileTemplates();
    }

    /**
     * Create an instance of {@link ServiceInfoDetailModel }
     * 
     */
    public ServiceInfoDetailModel createServiceInfoDetailModel() {
        return new ServiceInfoDetailModel();
    }

    /**
     * Create an instance of {@link StatisticsAgencyResultsModel }
     * 
     */
    public StatisticsAgencyResultsModel createStatisticsAgencyResultsModel() {
        return new StatisticsAgencyResultsModel();
    }

    /**
     * Create an instance of {@link StatisticsAgency }
     * 
     */
    public StatisticsAgency createStatisticsAgency() {
        return new StatisticsAgency();
    }

    /**
     * Create an instance of {@link StatisticsDomainResultsModel }
     * 
     */
    public StatisticsDomainResultsModel createStatisticsDomainResultsModel() {
        return new StatisticsDomainResultsModel();
    }

    /**
     * Create an instance of {@link StatisticsDomain }
     * 
     */
    public StatisticsDomain createStatisticsDomain() {
        return new StatisticsDomain();
    }

    /**
     * Create an instance of {@link ServiceInfoInputModel }
     * 
     */
    public ServiceInfoInputModel createServiceInfoInputModel() {
        return new ServiceInfoInputModel();
    }

    /**
     * Create an instance of {@link ServiceInfoSearchModel }
     * 
     */
    public ServiceInfoSearchModel createServiceInfoSearchModel() {
        return new ServiceInfoSearchModel();
    }

    /**
     * Create an instance of {@link FileTemplateModel }
     * 
     */
    public FileTemplateModel createFileTemplateModel() {
        return new FileTemplateModel();
    }

    /**
     * Create an instance of {@link ServiceInfoServiceConfig }
     * 
     */
    public ServiceInfoServiceConfig createServiceInfoServiceConfig() {
        return new ServiceInfoServiceConfig();
    }

    /**
     * Create an instance of {@link ServiceInfoRecentResultModel }
     * 
     */
    public ServiceInfoRecentResultModel createServiceInfoRecentResultModel() {
        return new ServiceInfoRecentResultModel();
    }

    /**
     * Create an instance of {@link ServiceInfoRecentResultModel }
     * 
     */
    public ServiceRecentDetailModel createServiceRecentDetailModel() {
        return new ServiceRecentDetailModel();
    }

}
