//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.09 at 04:40:11 PM ICT 
//


package org.opencps.dossiertemplate.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opencps.dossiertemplate.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opencps.dossiertemplate.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DossierTemplatePartListModel }
     * 
     */
    public DossierTemplatePartListModel createDossierTemplatePartListModel() {
        return new DossierTemplatePartListModel();
    }

    /**
     * Create an instance of {@link DossierPartModel }
     * 
     */
    public DossierPartModel createDossierPartModel() {
        return new DossierPartModel();
    }

    /**
     * Create an instance of {@link DossierTemplateInputModel }
     * 
     */
    public DossierTemplateInputModel createDossierTemplateInputModel() {
        return new DossierTemplateInputModel();
    }

    /**
     * Create an instance of {@link DossierTemplateModel }
     * 
     */
    public DossierTemplateModel createDossierTemplateModel() {
        return new DossierTemplateModel();
    }

    /**
     * Create an instance of {@link DossierPartResultsModel }
     * 
     */
    public DossierPartResultsModel createDossierPartResultsModel() {
        return new DossierPartResultsModel();
    }

    /**
     * Create an instance of {@link DossierPartInputModel }
     * 
     */
    public DossierPartInputModel createDossierPartInputModel() {
        return new DossierPartInputModel();
    }

    /**
     * Create an instance of {@link DossierTemplateResultsModel }
     * 
     */
    public DossierTemplateResultsModel createDossierTemplateResultsModel() {
        return new DossierTemplateResultsModel();
    }

}
