create table opencps_deliverable (
	uuid_ VARCHAR(75) null,
	deliverableId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	deliverableCode VARCHAR(75) null,
	deliverableName VARCHAR(75) null,
	deliverableType VARCHAR(75) null,
	govAgencyCode VARCHAR(75) null,
	govAgencyName VARCHAR(75) null,
	applicantIdNo VARCHAR(75) null,
	applicantName VARCHAR(75) null,
	subject VARCHAR(75) null,
	formData VARCHAR(75) null,
	formScript VARCHAR(75) null,
	formScriptFileId LONG,
	formReport VARCHAR(75) null,
	formReportFileId LONG,
	issueDate DATE null,
	expireDate DATE null,
	revalidate DATE null,
	deliverableState INTEGER,
	fileEntryId LONG,
	docSync INTEGER,
	dossierId LONG
);

create table opencps_deliverablelog (
	uuid_ VARCHAR(75) null,
	deliverableLogId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	deliverableId LONG,
	dossierUid VARCHAR(75) null,
	author VARCHAR(75) null,
	content VARCHAR(75) null,
	deliverableAction INTEGER,
	actionDate DATE null,
	payload VARCHAR(75) null
);

create table opencps_deliverabletype (
	uuid_ VARCHAR(75) null,
	deliverableTypeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	typeCode VARCHAR(75) null,
	typeName VARCHAR(75) null,
	formScriptFileId LONG,
	formReportFileId LONG,
	codePattern VARCHAR(75) null,
	counter LONG,
	mappingData VARCHAR(75) null,
	dataConfig VARCHAR(75) null,
	tableConfig VARCHAR(75) null,
	docSync INTEGER,
	govAgencies VARCHAR(75) null
);

create table opencps_deliverabletyperole (
	uuid_ VARCHAR(75) null,
	deliverableTypeRoleId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	deliverableTypeId LONG,
	roleId LONG,
	moderator BOOLEAN
);