create table opencps_dossier_tax (
	uuid_ VARCHAR(75) null,
	taxId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	dossierId LONG,
	dossierNo VARCHAR(75) null,
	maSoThue VARCHAR(75) null,
	soQuyetDinh VARCHAR(75) null,
	ngayQuyetDinh DATE null,
	tenTieuMuc VARCHAR(75) null,
	soTien INTEGER,
	hoTenNguoiNopTien VARCHAR(75) null,
	soCmtNguoiNopTien INTEGER,
	diaChiNguoiNopTien VARCHAR(75) null,
	tinhNguoiNopTien VARCHAR(75) null,
	huyenNguoiNopTien VARCHAR(75) null,
	xaNguoiNopTien VARCHAR(75) null,
	thoiGianThanhToan DATE null,
	soTienNop INTEGER,
	noiDungThanhToan VARCHAR(75) null,
	trangThaiThanhToan INTEGER,
	fileChungTu VARCHAR(75) null,
	ngayThueTraThongBao DATE null,
	ngayTraThongBao DATE null,
	ngayNhanBienLai DATE null
);

create table opencps_synctracking (
  uuid_ varchar(75) DEFAULT NULL,
  trackingId bigint(20) NOT NULL,
  companyId bigint(20) DEFAULT NULL,
  groupId bigint(20) DEFAULT NULL,
  userId bigint(20) DEFAULT NULL,
  userName varchar(75) DEFAULT NULL,
  createDate datetime(6) DEFAULT NULL,
  modifiedDate datetime(6) DEFAULT NULL,
  dossierNo varchar(75) DEFAULT NULL,
  referenceUid varchar(75) DEFAULT NULL,
  serverNo varchar(75) DEFAULT NULL,
  protocol varchar(75) DEFAULT NULL,
  stateSync int(11) DEFAULT NULL,
  serviceCode varchar(75) DEFAULT NULL,
  api varchar(200) DEFAULT NULL,
  fromUnit varchar(75) DEFAULT NULL,
  toUnit varchar(75) DEFAULT NULL,
  bodyRequest text DEFAULT NULL,
  response text DEFAULT NULL,
  metaData varchar(300) DEFAULT NULL,
  PRIMARY KEY (trackingId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8