create table opencps_dossier_tax (
	uuid_ VARCHAR(75) null,
	taxId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	dossierNo VARCHAR(75) null,
	maSoThue VARCHAR(75) null,
	soQuyetDinh VARCHAR(75) null,
	ngayQuyetDinh DATE null,
	tenTieuMuc VARCHAR(75) null,
	soTien INTEGER,
	hoTenNguoiNopTien VARCHAR(75) null,
	soCmtNguoiNopTien INTEGER,
	diaChiNguoiNopTien VARCHAR(75) null,
	tinhNguoiNopTien VARCHAR(75) null,
	huyenNguoiNopTien VARCHAR(75) null,
	xaNguoiNopTien VARCHAR(75) null,
	thoiGianThanhToan DATE null,
	soTienNop INTEGER,
	noiDungThanhToan VARCHAR(75) null,
	trangThaiThanhToan INTEGER,
	fileChungTu VARCHAR(75) null,
	ngayThueTraThongBao DATE null,
	ngayTraThongBao DATE null,
	ngayNhanBienLai DATE null,
	statusTBT INTEGER,
	statusCTT INTEGER
);

create table opencps_synctracking (
	uuid_ VARCHAR(75) null,
	trackingId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	dossierNo VARCHAR(75) null,
	referenceUid VARCHAR(75) null,
	serverNo VARCHAR(75) null,
	protocol VARCHAR(75) null,
	stateSync INTEGER,
	serviceCode VARCHAR(75) null,
	api VARCHAR(200) null,
	fromUnit VARCHAR(75) null,
	toUnit VARCHAR(75) null,
	bodyRequest TEXT null,
	response TEXT null,
	metaData VARCHAR(500) null
);